bbackend:
  name: github
  repo: LukasKlas/tj-sokol-chotec
  branch: main

media_folder: assets/images/uploads
public_folder: /assets/images/uploads

collections:
  - name: posts
    label: Aktuality
    folder: _posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: Nadpis, name: title, widget: string}
      - {label: Datum, name: date, widget: datetime}
      - {label: Titulni foto, name: image, widget: image, required: false}
      - {label: Obsah, name: body, widget: markdown}
      - {label: Kategorie, name: categories, widget: select,
         options: [Aktuality, Zapasy, Mladez, Klub]}